# Generated by Django 4.1.7 on 2023-07-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_managers_date_of_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directors',
            name='date_of_start',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workers',
            name='date_of_start',
            field=models.DateField(max_length=255),
        ),
    ]
